# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: molecole/proto/perform/perform_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='molecole/proto/perform/perform_service.proto',
  package='molecole.proto.perform',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,molecole/proto/perform/perform_service.proto\x12\x16molecole.proto.perform\"!\n\x0bPerformance\x12\x12\n\nactiveSlot\x18\x01 \x01(\x03\".\n\x17QueryPerformanceRequest\x12\x13\n\x0bproject_uid\x18\x01 \x01(\t2\x82\x01\n\x12PerformanceService\x12l\n\x10QueryPerformance\x12/.molecole.proto.perform.QueryPerformanceRequest\x1a#.molecole.proto.perform.Performance\"\x00\x30\x01\x62\x06proto3')
)




_PERFORMANCE = _descriptor.Descriptor(
  name='Performance',
  full_name='molecole.proto.perform.Performance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='activeSlot', full_name='molecole.proto.perform.Performance.activeSlot', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=105,
)


_QUERYPERFORMANCEREQUEST = _descriptor.Descriptor(
  name='QueryPerformanceRequest',
  full_name='molecole.proto.perform.QueryPerformanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_uid', full_name='molecole.proto.perform.QueryPerformanceRequest.project_uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['Performance'] = _PERFORMANCE
DESCRIPTOR.message_types_by_name['QueryPerformanceRequest'] = _QUERYPERFORMANCEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Performance = _reflection.GeneratedProtocolMessageType('Performance', (_message.Message,), dict(
  DESCRIPTOR = _PERFORMANCE,
  __module__ = 'molecole.proto.perform.perform_service_pb2'
  # @@protoc_insertion_point(class_scope:molecole.proto.perform.Performance)
  ))
_sym_db.RegisterMessage(Performance)

QueryPerformanceRequest = _reflection.GeneratedProtocolMessageType('QueryPerformanceRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPERFORMANCEREQUEST,
  __module__ = 'molecole.proto.perform.perform_service_pb2'
  # @@protoc_insertion_point(class_scope:molecole.proto.perform.QueryPerformanceRequest)
  ))
_sym_db.RegisterMessage(QueryPerformanceRequest)



_PERFORMANCESERVICE = _descriptor.ServiceDescriptor(
  name='PerformanceService',
  full_name='molecole.proto.perform.PerformanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryPerformance',
    full_name='molecole.proto.perform.PerformanceService.QueryPerformance',
    index=0,
    containing_service=None,
    input_type=_QUERYPERFORMANCEREQUEST,
    output_type=_PERFORMANCE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERFORMANCESERVICE)

DESCRIPTOR.services_by_name['PerformanceService'] = _PERFORMANCESERVICE

# @@protoc_insertion_point(module_scope)
